# Generated by Django 5.0.3 on 2024-03-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Numer pokoju')),
                ('room_type', models.CharField(choices=[('single', 'Jednoosobowy'), ('double', 'Dwuosobowy'), ('suite', 'Apartament')], max_length=10, verbose_name='Typ pokoju')),
                ('capacity', models.IntegerField(verbose_name='Pojemność')),
                ('beds', models.IntegerField(verbose_name='Liczba łóżek')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cena za noc')),
                ('available', models.BooleanField(default=True, verbose_name='Dostępność')),
                ('amenities', models.TextField(blank=True, verbose_name='Udogodnienia')),
            ],
            options={
                'verbose_name': 'pokój',
                'verbose_name_plural': 'pokoje',
            },
        ),
    ]
