# Generated by Django 5.0.3 on 2024-03-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_reservation_room_alter_reservation_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer_review',
            field=models.TextField(blank=True, null=True, verbose_name='Customer review'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Payment pending'), ('cancelled', 'Payment canceled')], max_length=30),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='service_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='amenities',
            field=models.TextField(blank=True, verbose_name='Amenities'),
        ),
        migrations.AlterField(
            model_name='room',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='room',
            name='beds',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], verbose_name='Number of beds'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], max_length=10, unique=True, verbose_name='Room number'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price per night'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('single', 'Double'), ('double', 'Twin'), ('suite', 'Trio'), ('family', 'Family')], max_length=10, verbose_name='Room type'),
        ),
    ]
